name: icount bench
on: [pull_request]

jobs:
  icount-benchmarks:
    name: Run icount benchmarks
    runs-on: ubuntu-22.04
    steps:
      - name: Install valgrind
        run: |
          sudo apt update
          sudo apt install -y valgrind
          valgrind --version

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Show gcc version
        run: gcc --version

      - name: Show clang version (if available)
        run: clang --version

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run icount benchmarks for PR
        run: cd ci-bench && cargo run --locked --release -- run-all --output-dir ${{ runner.temp }}/pr

      - name: Show compiler used for ring's C bits
        run: ls target/release/deps/libring-*.rlib | xargs objdump --full-contents --section=.comment
