name: trigger icount bench
on: [pull_request]

jobs:
  icount-benchmarks:
    name: Trigger icount benchmarks
    runs-on: ubuntu-22.04
    steps:
      # The next step was taken from https://github.com/actions/checkout/issues/58#issuecomment-1426758830
      - name: Get issue number
        uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Enqueue bench run on the bench server
        run: |
          curl -XPOST -H "Content-type: application/json" -d '{
              "api_secret": "${{secrets.rustls_perf_api_secret}}",
              "base_ref": "${{push.base_ref}}",
              "candidate_clone_url": "${{push.repository.clone_url}}",
              "candidate_ref": "$GITHUB_REF",
              "issue_number": "${{steps.get_issue_number.outputs.result}}"
          }' 'https://mint-guppy-happily.ngrok-free.app/api/bench'
